### ISSUE TITLE
Not compile

### ISSUE THREAD

**Issue by pavlinux** [reverbrain/elliptics#508]
$ git clone ....
$ cmake .
....
CMake Error at cmake/Modules/locate_library.cmake:13 (MESSAGE):
  react development files are required to build.
Call Stack (most recent call first):
  CMakeLists.txt:96 (locate_library)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
COCAINE_INCLUDE_DIRS (ADVANCED)
   used as include directory in directory /usr/src/elliptics/example/module_backend
   used as include directory in directory /usr/src/elliptics/example/module_backend
EBLOB_INCLUDE_DIRS (ADVANCED)
   used as include directory in directory /usr/src/elliptics/example/module_backend
   used as include directory in directory /usr/src/elliptics/example/module_backend

-- Configuring incomplete, errors occurred!

**Comment by molele2** [comment]
You need install 
mhash
binutils
libtool
libuuid
libcgroup
libarchive
handystats
blackhole
libev
cocaine-core,but you have new error
