### ISSUE TITLE
recovery broken? 

### ISSUE THREAD

**Issue by agend** [reverbrain/elliptics#570]
Gents,
  Tried last version and can't perform simple merge recovery. dnet_recovery script just stuck and nothing else. Did you test it?

**Comment by bioothod** [comment]
Please me more specific, in particular what does debug log level tell, what does stat file contain?
@shaitan please take a look

**Comment by agend** [comment]
@bioothod @shaitan Please take a look: https://yadi.sk/d/QEYV_msgeC79w
Also I can't stop it via CTRL-C

**Comment by agend** [comment]
Guys, Any new information on this?

**Comment by shaitan** [comment]
Hi @agend. I'm investigating your issue and will make a fix today.

**Comment by agend** [comment]
@shaitan Thanks.

**Comment by shaitan** [comment]
@agend which versions of eblob and elliptics did you use at the test?

**Comment by agend** [comment]
@shaitan eblob: 0.22.10 elliptics: 2.26.3.35

**Comment by agend** [comment]
Still no luck. Now it's can't find any keys to recover. Logs: https://yadi.sk/d/N0dNADd2eH2yu

**Comment by shaitan** [comment]
Is there any key that should be recovered? Can you describe what you do before recovering?

**Comment by agend** [comment]
1) Started empty node1
2) Filled with 20k records
3) Started one more empty node in the same group
4) Run recovery

**Comment by shaitan** [comment]
Could you provide logs of 2) stage?

**Comment by agend** [comment]
@shaitan Here you go: https://yadi.sk/d/f_qChYvoeJS7N

**Comment by shaitan** [comment]
@agend there is no write command at the log. Can you please rerun your case and provide client log while it writes 20k records and log of recovering?

**Comment by agend** [comment]
@shaitan  I have just checked file https://yadi.sk/d/f_qChYvoeJS7N and found this:
2015-01-28 19:45:12.735054 0000000000000000/3131/3087 NOTICE: 3d53caf3669af025: EBLOB: blob-write: WRITE: Ok: offset: 0, size: 10. 'backend_id': 1
2015-01-28 19:45:12.735085 0000000000000000/3107/3087 INFO: 0:0000000000000000...0000000000000000: ROUTE_LIST: client: 127.0.0.1:46501, trans: 1, cflags: 0x18 [direct|nolock], time: 379 usecs, err: 0. 

I think this one is write command or I missing something?

**Comment by agend** [comment]
@bioothod Or this 
2015-01-28 19:45:12.732134 0000000000000000/3122/3087 DEBUG: 127.0.0.1:46499: 2:568aada19326d467...0000000000000005: RECV cmd: WRITE: cmd-size: 218, nonblocking: 0

**Comment by bioothod** [comment]
There are 20k writes in the log indeed.
Thanks @agend we are looking at it

**Comment by agend** [comment]
@shaitan Kirill, did you have chance to take a look on this issue?

**Comment by agend** [comment]
@shaitan  updating eblob to 0.22.16 fixed issue with empty iterator in while recovering. But i got a new one: recovery process just stop after recoverd 690 of 20000 records. Also @bioothod There are no new rpm version of eblob on repo.reverbrain.com

**Comment by agend** [comment]
@bioothod @shaitan Gents do you have any news on this issue?

**Comment by bioothod** [comment]
Kirill is on vacations, he will take a look when return.
I will also try to figure out what has happened

**Comment by agend** [comment]
Cool, thanks.
If you need more details or run test - just ask.
