### ISSUE TITLE
Improve oplocks

### ISSUE THREAD

**Issue by shaitan** [reverbrain/elliptics#597]
# Introduction
**Oplocks** is mechanism that is used by `dnet_ioserv` for ordering access to stored keys. All commands without `DNET_COMMAND_FLAGS_NOLOCK` go through **oplocks** and are executed with unique ownership of the used key.

# Current oplocks behaviour and restrictions
## Main structure
All locked keys are kept in `dnet_locks` object that consists of:
 * locked keys rbtree
 * list of preallocated entries that will be used at rbtree. Currently, `dnet_ioserv` preallocates **1024** entries, it means only **1024** different keys can be locked at one moment  and only **1024** threads can executes commands
 * lock that is used for ordering access to `dnet_locks`

## How does it work
When `io pool` thread takes a request from queue, it tries to lock the key from the request:
 * if the key is already locked - the thread will wait until the key is free
 * if the key is free:
  * if not all preallocated entries are used - the thread locks the key
  * if all preallocated entries are used - the thread handles request without lock

It means:
* if we have intensive streams of commands with non-unique keys, part of threads will wait keys while there are requests with unlocked keys in the queue
* `dnet_locks` is global for the server node, if we have a lot of backends and the total number of threads at all backends is more than **1024**, we have a risk to execute a command by pass **oplocks**
* locked keys don't include **group_id** or **backend_id** at which they are locked. If we have a blocking commands for the same key in 2 backends, for example, if we have 2 backends that are replicates each other, these 2 backends will compete for keys and each time one backend will wait until another unlock a key.

# What are we trying to accomplish
 * exclude preallocation limit to **1024**
 * escape waiting locked key by `io pool` thread if the queue has requests with unlocked keys
 * make locks at different backends independent

# How can we accomplish it
## Exclude preallocation limit to **1024**
Use a container with reservation but not preallocation. Also splitting node-wide `dnet_locks` onto number of backend-wide `dnet_locks` will help.

## Escape waiting locked key
Make an queue wrapper that will allows to get next request with unlocked key or will wait for it. Also this wrapper should guarantee that requests from the queue for the same key will be handled in the same order as they are presented in the queue.

## Make locks at different backends independent
Move `dnet_locks` into `dnet_backend_io`. Each backend will keep only keys that is locked by this backend.

**Comment by abudnik** [comment]
https://github.com/reverbrain/elliptics/pull/636
