### ISSUE TITLE
API: allow server to send its keys to different groups

### ISSUE THREAD

**Issue by bioothod** [reverbrain/elliptics#600]
# Current state
Server doesn't have API to send its keys to other groups. This forces recovery process to read data from one group and send it to missing replicas.

# What is wanted to be changed
If server would be told to send some keys to other groups (according to merged iterated keys) this will remove expensive data transfers (even when key is stored on the same machine as where recovery runs) and will allow external agents to watch and start recovery (currently they have to download data from 'good' replica and then write it to missing groups).

**Comment by bioothod** [comment]
https://github.com/reverbrain/elliptics/pull/650

**Comment by agend** [comment]
Is it already usable in recovery?

**Comment by bioothod** [comment]
It is not used in `dnet_recovery` tool yet, but you can use it on your own

**Comment by agend** [comment]
Do you have any estimation on when ot will be available in dnet_recovery
tool?

**Comment by bioothod** [comment]
@shaitan Kirill, do you?

**Comment by shaitan** [comment]
At the end of this or early next week we will start working on it.

**Comment by agend** [comment]
Thanks!

**Comment by lpaulmp** [comment]
Nice
