### ISSUE TITLE
Weights: split node weight to backends weights

### ISSUE THREAD

**Issue by shaitan** [reverbrain/elliptics#601]
# Current state
At the beginning weight of each node is equal to 1. After each read/write command client recalculates weight of the node that has handled the command. When client starts new read command it gets weights of all nodes that could have reading key and randomly in accordance with weights choose the node that will be requested at first.
If some node has a backend that worsens weights because, for example, its device is under heavy io operations, other backends on the same node will get less traffic than they could handle.

# What is wanted to be changed
Split 'weight per node' into 'weight per backend'. Each backend should have independent weight and client should choose node based on backends weights that could handle the command, possibly considering weights of the nodes, that shows network conditions between client and each node.

**Comment by abudnik** [comment]
done
