### ISSUE TITLE
dnet_recovery log levels

### ISSUE THREAD

**Issue by agend** [reverbrain/elliptics#626]
Found in code the dnet_recovery always use DEBUG level to write to file:
https://github.com/reverbrain/elliptics/blob/master/recovery/elliptics_recovery/dc_recovery.py#L487
and the same in recovery.py
https://github.com/reverbrain/elliptics/blob/master/recovery/elliptics_recovery/recovery.py#L144

Overall strange log level assigment:
https://github.com/reverbrain/elliptics/blob/master/recovery/elliptics_recovery/dc_recovery.py#L461
and then
https://github.com/reverbrain/elliptics/blob/master/recovery/elliptics_recovery/dc_recovery.py#L479

Similar things in https://github.com/reverbrain/elliptics/blob/master/recovery/elliptics_recovery/recovery.py

**Comment by bioothod** [comment]
There are 2 logs: stderr and file, the former uses info level, the latter debug one to catch all issues.
If client sets '-d' command line option, stderr output prints debug level events too

**Comment by agend** [comment]
Is there way to disable debug level for file output?

**Comment by bioothod** [comment]
No at the moment, but why is this needed?
It was deliberately done to catch up all cases, if you disable this, we will not be able to debug recovery

**Comment by agend** [comment]
too much logs for no reason: taking lots of space + recovery speed i think will be better

**Comment by shaitan** [comment]
Recovery can use `-L` parameter for both elliptics and recovery logs. I will make it soon.

**Comment by agend** [comment]
Cool, thx
