### ISSUE TITLE
Build without examples

### ISSUE THREAD

**Issue by noxiouz** [reverbrain/elliptics#654]
Seems **WITH_EXAMPLES** flag doesn't make sense, as **libelliptics.so** can NOT be linked without <strike>patching ld.so.conf and rebuilding boost</strike> turrning this flag on:
```
Linking CXX shared library libelliptics.so
/usr/bin/ld: cannot find -lelliptics_common
collect2: ld returned 1 exit status
```
I'm not a real welder, but that's because **libelliptics_common** is added only in **example/CMakeLists.txt**
Is it on purpose?

**Comment by bioothod** [comment]
I've dropped `WITH_EXAMPLES` config option, although it was always on.
I'm not sure why can't you build `libelliptics`, it includes `libelliptics_common` as well as bunch of other libs, but it should be correctly handled by cmake

**Comment by bioothod** [comment]
Looks like it is resolved now
