### ISSUE TITLE
Exception raised when session hasn't exceptions_policy.no_exceptions after server_send operation

### ISSUE THREAD

**Issue by abudnik** [reverbrain/elliptics#665]
`Error: insufficient results count due to checker: 0 of 4 (0): No such device or address: -6`

**Comment by bioothod** [comment]
Do you have a trace for the origin of the exception?
Command to reproduce, logs, anything?

**Comment by abudnik** [comment]
```
$> git diff
diff --git a/tests/server_send.cpp b/tests/server_send.cpp
index b83f889..65f0bd6 100644
--- a/tests/server_send.cpp
+++ b/tests/server_send.cpp
@@ -278,7 +278,7 @@ static bool ssend_register_tests(test_suite *suite, node &n)

        session src(n);
        src.set_groups(ssend_src_groups);
-       src.set_exceptions_policy(session::no_exceptions);
+       //src.set_exceptions_policy(session::no_exceptions);
        src.set_timeout(120);

        uint64_t iflags = DNET_IFLAGS_MOVE | DNET_IFLAGS_DATA;
```
This is the simplest way to reproduce this issue.

**Comment by bioothod** [comment]
Do I get your problem correctly: you catch exception if you do not set `no-exception` flag?
Just like you catch exception when you write data into non-existing group without `no-exception` flag?

**Comment by abudnik** [comment]
Yes, after that test prints to stdout:
```
Set base directory: "/home/abudnik/elliptics/obj-x86_64-linux-gnu/tests/result/dnet_server_send_test"
Set cocaine run directory: "/tmp/elliptics-test-run-6c52abc5/"
Starting 3 servers
Starting server #1
Started server #1
Starting server #2
Started server #2
Starting server #3
Started server #3
Started servers
Running 21 test cases...
unknown location(0): fatal error in "(ssend_test_read_many_keys_error, src, num, id_prefix, -2)": std::exception: 1:9458b7bca10b...b760eff21c5b: Failed to process READ command: No such file or directory: -2
/home/abudnik/elliptics/tests/server_send.cpp(220): last checkpoint
unknown location(0): fatal error in "(ssend_test_read_many_keys_error, src, num, id_prefix, -2)": std::exception: 1:9458b7bca10b...b760eff21c5b: Failed to process READ command: No such file or directory: -2
/home/abudnik/elliptics/tests/server_send.cpp(220): last checkpoint
unknown location(0): fatal error in "(ssend_test_server_send, src, num, id_prefix, data_prefix, ssend_dst_groups, iflags)": std::exception: insufficient results count due to checker: 0 of 8 (0): No such device or address: -6
/home/abudnik/elliptics/tests/server_send.cpp(234): last checkpoint
unknown location(0): fatal error in "(ssend_test_read_many_keys_error, src, num, id_prefix, -2)": std::exception: 1:dfd9eb746bd9...3ae9c9467649: Failed to process READ command: No such file or directory: -2
/home/abudnik/elliptics/tests/server_send.cpp(234): last checkpoint
```

**Comment by bioothod** [comment]
Elliptics raises exception on error unless it was told not to do it via setting `session::no_exceptions` policy. That's how it works.

If you want error code, you have to set `session::no_exceptions` session policy.
I do not see what is wrong with this issue, why do you think this is a bug.

**Comment by abudnik** [comment]
Exception raised even if no error occurs, that is the problem. I've tried to call server_send() and got -6 error, but there were not errors in the log.

**Comment by bioothod** [comment]
How did you manage to get it without log string?
Was it sending data into nonexisting group, or was it iteration over nonexisting group?

If you do not disable exceptions, elliptics test above will explode with exceptions trying to read data from groups, where it has failed to write data to. This is not what you describe in the last comment.

**Comment by abudnik** [comment]
I will write a small demo that reproduces this problem soon.

**Comment by bioothod** [comment]
Great! Let me know

**Comment by abudnik** [comment]
Yes, it fixes the problem.
