### ISSUE TITLE
Reverbrain.com blog hacked

### ISSUE THREAD

**Issue by voxadam** [reverbrain/elliptics#725]
I thought someone might like to know that the blog at http://reverbrain.com/blog/ appears to have succumb to some sort of vulnerability. There are a few posts such as "The Best Online Pharmacy. Buy Cialis Without Prescription – Orders-Cialis.info" and "Watch Full Movie Jackie (2016)" that I find rather suspect.

**Comment by bioothod** [comment]
Wow, thank you, we have updated it!

**Comment by voxadam** [comment]
No problem. That's what I'm here for.
