### ISSUE TITLE
Elliptics logs and log rotate 

### ISSUE THREAD

**Issue by 6ecuk** [reverbrain/elliptics#728]
Hi, seems have the same problem https://github.com/3Hren/blackhole/issues/58, how you win this issue ? And another question - any plans for update blackhole versions? Thanks.

**Comment by bioothod** [comment]
Changing blackhole dependencies will break other applications which will become binary incompatible. Unfortunately we can not force everyone to rebuild their binaries just because we have changed the logger.

**Comment by 6ecuk** [comment]
Okey, but how fix problem with log rotate ? Restart elliptics services every rotate - not best idea i think.

**Comment by agend** [comment]
We are using option with syslog.

**Comment by 6ecuk** [comment]
Can you show  log rotate config example. Thanks

**Comment by agend** [comment]
```
"logger": {
               "level": "error",
               "frontends": [
                       {
                               "formatter": {
                                       "type": "string",
                                       "pattern": "%(timestamp)s %(request_id)s/%(lwp)s/%(pid)s %(severity)s: %(message)s %(...L)s"
                               },
                               "sink": {
                                       "type": "syslog",
                                       "identity": "elliptics"
                               }
                       }
               ]
       }
```

**Comment by 6ecuk** [comment]
Thanks.
