### ISSUE TITLE
Suddenly oom

### ISSUE THREAD

**Issue by 6ecuk** [reverbrain/elliptics#729]
Good evening. I have two nodes with almost the same configurations. First node working stable more than year. But second node suddenly go in oom. Centos 7 on both nodes. First i think problem was in log rotation issues, so i changed from writing directly in file to  syslog usage. But this not helped.  Node 2 catches oom once per month. Difference between nodes i found - its  just minor version of handy stats 1.11.3-5.el7 vs handystats.x86_64 1.11.3-1.

Node1 |Node2
------------ | -------------
elliptics.x86_64 2.26.11.1-2.el7 reverbrain |elliptics.x86_64  2.26.11.1-2.el7.R reverbrain
 handystats.x86_64 1.11.3-5.el7.R @russianfedora-free-updates|handystats.x86_64 1.11.3-1.el7 reverbrain
 eblob-libs.x86_64    0.23.14-1.el7.R  russianfedora-free-updates |
 eblob.x86_64   0.23.14-1.el7.1 reverbrain |eblob.x86_64 0.23.14-1.el7.1 reverbrain    
 eblob-debuginfo.x86_64 0.23.14-1.el7.1 reverbrain | eblob-debuginfo.x86_64 0.23.14-1.el7.1 reverbrain    
 eblob-devel.x86_64  0.23.14-1.el7.1  reverbrain | eblob-devel.x86_64  0.23.14-1.el7.1  reverbrain

**Comment by bioothod** [comment]
Do I get it right, that upgrading handystats fixes the problem?

**Comment by 6ecuk** [comment]
Minor version update not helped. Disable handystats in config.
