### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by avanov** [reverbrain/elliptics#734]
subj

**Comment by bioothod** [comment]
There are no active contributions at the moment

**Comment by avanov** [comment]
Hi @bioothod, thanks for your reply.

I'd like to revive it at least to the point where the project could reproducibly build itself with Nix, but since both of the links mentioned in the README don't point me to the proper build entry point, would you be able to assist me in finding rendered documentation pages that explain the current pipeline? Also, how much are you interested in continuing this project and evolving it over time through community effort and updates (switching docs format for easier access and overall discoverability of information, organising CI in the current repo, and so on and so forth)?

What is the current story with Yandex.Cocaine components? Does the project depend on them or is it more like an addon?

Sorry if some of the questions are silly, last time I looked at Elliptics it was 10 years ago, and a lot has changed since then. I'm currently in a search for a solution that would allow for a more performant and more compact binary store format than the currently available popular alternatives (MinIO and alike), and I remembered Elliptics presentation from one of the earliest YaC events.

**Comment by avanov** [comment]
Potentially, in a long run (and without a definitive commitment), I'd like to provide [ATS bindings](http://www.ats-lang.org/#What_is_ATS_good_for) to the existing C API. I wonder if that could be of interest to anyone following this repo.

**Comment by agend** [comment]
Hi @avanov I have used elliptics for many years. As the project was frozen for quite a while we decided to develop something in-house (why not). If you interested you can check https://github.com/qoollo/bob . It was inspired by elliptics and something we learned running it.

**Comment by avanov** [comment]
@agend fantastic! I'll check it out.

@bioothod I'm still interested in hearing from you too, as I'm assessing all available options now.

**Comment by zhituha** [comment]
I liked Elliptics! Good night, sweet prince!

**Comment by bioothod** [comment]
Thank you, it is sad the project hasn't developed the way it was intended to
